version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT = 5000
      - MONGO_URI = mongodb://localhost:27017/
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    command: >
      sh -c "
        echo 'Waiting for MongoDB to be ready...'
        sleep 5
        npm start
      "

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
